testesRazor/Models/VeiculosModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace testesRazor.Models
{
    public class VeiculosModel
    {
        public VeiculosModel(int id, string plate, int type)
        {
            Id = id;
            Plate = plate;
            Type = type;
        }

        public int Id { get; set; }
        public string Plate { get; set; }
        public int Type { get; set; }
    }
}

testesRazor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace testesRazor.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

testesRazor/Controllers/VeiculosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using testesRazor.Models;

namespace testesRazor.Controllers
{
    public class VeiculosController : Controller
    {
        // GET: Veiculos
        public ActionResult Index()
        {
            var listOfVehicles = new List<VeiculosModel>();
            listOfVehicles.Add(new VeiculosModel(1, "teste", 2));

            listOfVehicles.Add(new VeiculosModel(2, "teste2", 2));

            listOfVehicles.Add(new VeiculosModel(3, "teste3", 2));

            listOfVehicles.Add(new VeiculosModel(4, "teste4", 2));
            listOfVehicles.Add(new VeiculosModel(5, "teste", 2));

            listOfVehicles.Add(new VeiculosModel(6, "teste2", 2));

            listOfVehicles.Add(new VeiculosModel(7, "teste3", 2));

            listOfVehicles.Add(new VeiculosModel(8, "teste4", 2));
            listOfVehicles.Add(new VeiculosModel(9, "teste", 2));

            listOfVehicles.Add(new VeiculosModel(10, "teste2", 2));

            listOfVehicles.Add(new VeiculosModel(11, "teste3", 2));

            listOfVehicles.Add(new VeiculosModel(12, "teste4", 2));
            listOfVehicles.Add(new VeiculosModel(13, "teste", 2));

            listOfVehicles.Add(new VeiculosModel(14, "teste2", 2));

            listOfVehicles.Add(new VeiculosModel(15, "teste3", 2));

            listOfVehicles.Add(new VeiculosModel(16, "teste4", 2));
            listOfVehicles.Add(new VeiculosModel(17, "teste", 2));

            listOfVehicles.Add(new VeiculosModel(18, "teste2", 2));

            listOfVehicles.Add(new VeiculosModel(19, "teste3", 2));

            listOfVehicles.Add(new VeiculosModel(20, "teste4", 2));
            listOfVehicles.Add(new VeiculosModel(21, "teste", 2));

            listOfVehicles.Add(new VeiculosModel(22, "teste2", 2));

            listOfVehicles.Add(new VeiculosModel(23, "teste3", 2));

            listOfVehicles.Add(new VeiculosModel(24, "teste4", 2));
            listOfVehicles.Add(new VeiculosModel(25, "teste", 2));

            listOfVehicles.Add(new VeiculosModel(26, "teste2", 2));

            listOfVehicles.Add(new VeiculosModel(27, "teste3", 2));

            return View(listOfVehicles);
        }

        // GET: Veiculos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Veiculos/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Veiculos/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Veiculos/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

   
        // POST: Veiculos/Delete/5
        [HttpPost]
        public JsonResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return Json(new { response = "deletado" + id });
            }
            catch
            {
                return Json(new { response = "deletado" + id });
            }
        }
    }
}

testesRazor/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

testesRazor/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

testesRazor/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

testesRazor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/script.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.material.min.css" rel="stylesheet" />
    <link type="text/css" href="~/Content/Site.css" rel="stylesheet" />

    <script>
        $(document).ready(function () {
            $('.sidenav').sidenav();
        });
    </script>

</head>
<body>
    <nav>
        <a href="#" data-target="slide-out" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
    </nav>

    <ul id="slide-out" class="sidenav">
        <li><a class="waves-effect" href="@Url.Action("Index", "Veiculos")">Veiculos</a></li>
        <li><a class="waves-effect" href="#!">Item De Menu 2</a></li>
    </ul>
    <div class=" body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year    - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/materialize")
    @RenderSection("scripts", required: false)
</body>
</html>

testesRazor/Views/Veiculos/Index.cshtml
@using testesRazor.Models
@model IEnumerable<VeiculosModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    $(document).ready(function () {

        $(".Edit").on('click', function (event) {
            event.stopPropagation();
            event.stopImmediatePropagation();
            var row = $(this).closest("tr");
            exibirInputs(row);
            exibirBotoesAtualizaCancela(row);
        });

         $(".Cancel").on('click', function (event) {
            event.stopPropagation();
            event.stopImmediatePropagation();
            var row = $(this).closest("tr");
            ocultarInputs(row);
            ocultarBotoesAtualizaCancela(row);
            alert("cancel");
         })

           $(".Update").on('click', function (event) {
            event.stopPropagation();
            event.stopImmediatePropagation();
            var row = $(this).closest("tr");
            ocultarInputs(row);
            ocultarBotoesAtualizaCancela(row);
            alert("UPDATE");
           })

         $(".Delete").on('click', function (event) {
            event.stopPropagation();
            event.stopImmediatePropagation();
            var row = $(this).closest("tr");
            ocultarBotoesAtualizaCancela(row);

          alert("Delete");
         })

        function exibirBotoesAtualizaCancela(row) {
            row.find(".Update").show();
            row.find(".Cancel").show();
            row.find(".Delete").hide();
            row.find(".Edit").hide();
        }
        function ocultarBotoesAtualizaCancela(row) {

            row.find(".Update").hide();
            row.find(".Cancel").hide();
            row.find(".Delete").show();
            row.find(".Edit").show();
        }

        function exibirInputs(row) {
            $("td", row).each(function () {
            if ($(this).find("input").length > 0) {
                $(this).find("input").show();
                $(this).find("span").hide();
            }
             });
        }
        function ocultarInputs(row) {
               $("td", row).each(function () {
                if ($(this).find("input").length > 0) {
                    $(this).find("input").hide();
                    $(this).find("span").show();
                }
            });
        }
    });
    
       
     $.ajax({
                method: "POST",
                url: "https://localhost:44381/Veiculos/Edit/" + row.val(),
                data: { id: id }
            }).done(function (msg) {
                //alert(JSON.stringify(msg));
            })

</script>


<div class="row">
    <div id="man" class="col s12">
        <div class="card material-table">
            <div class="table-header">
                <span class="table-title">Lista de Veiculos</span>
                <div class="actions">
                    <a href="#" class="modal-trigger waves-effect btn-flat nopadding"><i class="material-icons">person_add</i></a>
                    <a href="#" class="search-toggle waves-effect btn-flat nopadding"><i class="material-icons">search</i></a>
                </div>
            </div>
            <table id="datatable" class="mdl-data-table" style="width:100%">
                <thead>
                    <tr>
                        <th>Tipo do Veiculo</th>
                        <th>Placa</th>
                        <th>
                        </th>

                    </tr>
                </thead>

                <tbody id="myTable">

                    @foreach (var item in Model)
                    {
                        <tr id="row@{@item.Id}">
                            <td>
                                <span>@item.Id</span>
                                <input type="text" value="@item.Id" style="display:none" />
                            </td>

                            <td>
                                <span>@item.Plate</span>
                                <input type="text" id="input-edit@{@item.Id}" value="@item.Plate" style="display:none" />
                            </td>

                            <td>
                                <a value="@item.Id" id="edit@{@item.Id}" class="Edit waves-effect waves-light "><i class="material-icons">edit</i></a>
                                <a class="Update" id="update@{@item.Id}" href="javascript:;" style="display:none">Update</a>
                                <a class="Cancel" id="cancel@{@item.Id}" href="javascript:;" style="display:none">Cancel</a>
                                <a value="@item.Id" id="delete@{@item.Id}" class="Delete waves-effect waves-light" onclick="deleteVehicle('@item.Id')"><i class="material-icons">delete</i></a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>


        </div>
    </div>
</div>